### ISSUE TITLE
Maxroll chest import issue

### ISSUE THREAD

**Issue by TheOne320** [d4lfteam/d4lf#398]
Version 5.8.10

When importing this build:

https://maxroll.gg/d4/planner/1p8k0pan#9

The chest is this:
![image](https://github.com/user-attachments/assets/af38c7e4-ffc8-44a7-8ded-b8952d27d975)
But the profile after importing is this:
```
Affixes:
- ChestArmor:
    affixPool:
    - count:
      - {name: maximum_life}
      - {name: dexterity}
      - {name: armor}
      minCount: 2
      minGreaterAffixCount: 0
    itemType: [chest armor]
    minPower: 100
```

The chest should not have armour.
