### ISSUE TITLE
Validation Error when trying to scrape from D4Builds

### ISSUE THREAD

**Issue by DamianWing** [d4lfteam/d4lf#466]
Traceback (most recent call last):
  File "gui\importer\d4builds.py", line 115, in import_d4builds
  File "pydantic\main.py", line 253, in __init__
pydantic_core._pydantic_core.ValidationError: 1 validation error for AspectUniqueFilterModel
name
  Value error, aspect sidhe_bindings does not exist [type=value_error, input_value='Sidhe Bindings', input_type=str]
    For further information visit https://errors.pydantic.dev/2.11/v/value_error

**Comment by cjshrader** [comment]
Thank you Damian, can you please provide the build you are trying to import and I'll take a look. Looks like we're missing the unique in our uniques file

**Comment by DamianWing** [comment]
Hi cj, im trying to import the lightning spear sorc from the endgame section

**Comment by cjshrader** [comment]
Sorry, would you mind linking the specific link you are trying to import when you get a chance? Sometimes different links work differently.

**Comment by DamianWing** [comment]
https://d4builds.gg/builds/ddd34be3-c267-4330-8b76-ff6f6164a49f/?var=1

I hope this helps

**Comment by cjshrader** [comment]
This will be fixed in the next release, below is what the generated profile will look like for now.

``` yaml
# https://d4builds.gg/builds/ddd34be3-c267-4330-8b76-ff6f6164a49f/?var=1
# 2025-05-03 13:12:44 (v7.1.0)
Affixes:
- Amulet:
    affixPool:
    - count:
      - {name: intelligence}
      - {name: to_primordial_binding}
      - {name: to_glass_cannon}
      minCount: 2
      minGreaterAffixCount: 0
    itemType: [amulet]
    minPower: 100
- Boots:
    affixPool:
    - count:
      - {name: intelligence}
      - {name: maximum_life}
      - {name: mana_per_second}
      minCount: 2
      minGreaterAffixCount: 0
    inherentPool:
    - count:
      - {name: attacks_reduce_evades_cooldown_by_seconds}
    itemType: [boots]
    minPower: 100
- Legs:
    affixPool:
    - count:
      - {name: intelligence}
      - {name: maximum_life}
      - {name: armor}
      minCount: 2
      minGreaterAffixCount: 0
    itemType: [pants]
    minPower: 100
- Ring:
    affixPool:
    - count:
      - {name: critical_strike_chance}
      - {name: critical_strike_damage}
      - {name: attack_speed}
      minCount: 2
      minGreaterAffixCount: 0
    itemType: [ring]
    minPower: 100
- Staff:
    affixPool:
    - count:
      - {name: intelligence}
      - {name: critical_strike_damage}
      - {name: maximum_life}
      minCount: 2
      minGreaterAffixCount: 0
    itemType: [staff]
    minPower: 100
Uniques:
- aspect: {name: hail_of_verglas}
  affix:
  - {name: to_ice_shards}
  - {name: intelligence}
  - {name: attack_speed}
  - {name: cooldown_reduction}
- aspect: {name: tal_rashas_iridescent_loop}
  affix:
  - {name: nonphysical_damage}
  - {name: cooldown_reduction}
  - {name: lucky_hit_chance}
  - {name: to_potent_warding}
- aspect: {name: raiment_of_the_infinite}
  affix:
  - {name: intelligence}
  - {name: to_elemental_attunement}
  - {name: to_shocking_impact}
  - {name: to_glass_cannon}
- aspect: {name: sidhe_bindings}
  affix:
  - {name: chance_for_familiars_to_hit_twice}
  - {name: familiar_explosion_size}
  - {name: to_familiar}
  - {name: to_primordial_binding}
```
