### ISSUE TITLE
question:  how to "or" two or more affixPool

### ISSUE THREAD

**Issue by kngharv** [d4lfteam/d4lf#475]
I am trying to type the config file by hand.

I am struggling with implementing this concept of "or" in different affixPool

For example:

in chest armor,  I want to keep a chest armor that is either has resistance_to_all_elements OR to_golem_mastery.

And my config file is this:

```
# logic "or" howto
# 2025-05-06 00:05:14 (v7.1.1)
Affixes:

- chest:
    affixPool:
    - count:
      - {name: resistance_to_all_elements, value: null, comparison: larger}
      minCount: 1
      minGreaterAffixCount: 0
    - count:
      - {name: to_golem_mastery, value: null, comparison: larger}
      minCount: 1
      minGreaterAffixCount: 0
    itemType: [chest armor]
    minPower: 700

```
In this simple case, I know I can simply lump both affixes to a single affixPool and do a "minCount: 1"

what happened if I want to implement an "or" in different affixPool?  For example, in one pool, i want two out of three
- intelligence
- max_life
- resistance_to_all_elements

and another affixPool in which I want one of the following:
- to_golem_mastery
- to_corpse_explosion

what i want is:  if either affixPool matches, it will keep it.

1. does this tool support such logic?
2. if so, how to do that in a yaml file?

**Comment by cjshrader** [comment]
Unless I'm not following, I think your best bet in this case would be to make two different "chests".

You'd have 1 with int/max life/res, and 1 with to_golem_mastery and to_corpse_explosion.

**Comment by jpetays** [comment]
Maybe this example helps you to get on the right track :-)
You put most important items higher and D4LF will show them on top of lower priority items.
I mark items using following syntax:
- **BIS**
- **E**ndgame [n]
- **L**evelling [n]

[S8_Minions_v2.yaml.txt](https://github.com/user-attachments/files/20062762/S8_Minions_v2.yaml.txt)

**Comment by kngharv** [comment]
> Unless I'm not following, I think your best bet in this case would be to make two different "chests".
> 
> You'd have 1 with int/max life/res, and 1 with to_golem_mastery and to_corpse_explosion.

Thank you.  

In summary:
Having multiple entries of same gear type (e.g. chest armor, helm, ring, etc) is how you implement "or"

as an example:

```
- chest:
    affixPool:
    - count:
      - {name: resistance_to_all_elements}
      minCount: 1
      minGreaterAffixCount: 0
    itemType: [chest armor]
    minPower: 700
- chest:
    affixPool:
    - count:
      - {name: to_golem_mastery}
      minCount: 1
      minGreaterAffixCount: 0
    itemType: [chest armor]
    minPower: 700
```
means EITHER to_golem_mastery OR resistance_to_all_elements will be selected.  

That is all I need.   Thanks.  And much appreciate the tool, man !
