### ISSUE TITLE
"Codex Upgrade" hides other loot filter messages

### ISSUE THREAD

**Issue by jpetays** [d4lfteam/d4lf#489]
I is sometimes unfortunate that **orange** `Codex Upgrade` text hides other loot filter **green** messages.
It might be that this is the case always that item is not scanned to the end when Codex Upgrade is detected!?

It would be beneficial to fully evaluate the item and show green messages even item is highlighted as orange for Codex Upgrade.

I have typically this kind of section to highlight certain items for me as they can be valuable.
Now I noticed that this is not honored due to Codex Upgrade :-(

````yaml
  - MOVE:
    itemType: [ boots,amulet ]
    affixPool:
      - count:
          - { name: movement_speed }
        minCount: 1
  - RANKS:
    itemType: [ helm,gloves,pants,amulet ]
    affixPool:
      - count:
          - { name: to_envenom }
          - { name: to_quickshift }
          - { name: to_shred }
        minCount: 1
````

![Image](https://github.com/user-attachments/assets/9be0db75-9033-49c8-a29a-77dbbc0de52f)
